
version: "3.9"

services:
    frontend:
        ports:
          - "${WEB_PORT}:80"
    backend:
        environment:
          API_PORT: "${API_PORT}"
          MONGODB_USER_NAME: admin
          MONGODB_USER_PASSWORD: adminExam2022
          MONGODB_DB_NAME: SOSU-Final-Release
          JWT_SECRET_KEY: justALittleSecret
          JWT_EXPIRATION_TIME: 4300s
        ports:
            - "${API_PORT}:3006"
