version: "3.9"

services:
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
  frontend:
    build:
      context: "sosusystem-frontend"
    image: "localhost:7002/sosusystem-frontend:${IMAGE_TAG}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
  backend:
    build:
      context: "sosusystem-backend"
      target: production
    image: "localhost:7002/sosusystem-backend:${IMAGE_TAG}"
    command: npm run start
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"
    depends_on:
      - mongo
    volumes:
      - /node_modules
      
volumes:
  mongo:
