version: "3.9"

services:
    
  web:
  
    build:
      context: "Web"
    image: "localhost:7002/weather-web:${IMAGE_TAG}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"

