version: "3.9"

services:
  frontend:
    build:
      context: "sosusystem-frontend"
    image: "localhost:7002/sosusystem-frontend:${IMAGE_TAG}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
  backend:
    build:
      context: "sosusystem-backend"
    image: "localhost:7002/sosusystem-backend:${IMAGE_TAG}"
    container_name: "${API_CONT_NAME}"
    entrypoint: ["npm", "run", "start"]
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - mongo_db
    environment:
      MONGODB_USER_NAME: admin
      MONGODB_USER_PASSWORD: adminExam2022
      MONGODB_DB_NAME: SOSU-Final-Release
      JWT_SECRET_KEY: justALittleSecret
      JWT_EXPIRATION_TIME: 4300s
    networks: 
      - container-network
  mongo_db:
    image: mongo
    restart: always
    container_name: mongo_container # Use this in the connection url
    command: mongod -port 27017 --dbpath /data/db --replSet rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo_storage:/data/db
    networks: 
      - container-network

volumes:
  mongo_storage:

networks: 
  container-network:
    name: container-network
    driver: bridge
