version: "3.9"

services:
    api:
        image: andersmadsen0/sosusystem-backend:${BUILD_NUMBER}
        restart: always
    web:
        image: andersmadsen0/sosusystem-frontend:${BUILD_NUMBER}
        restart: always
