version: "3.9"

services:
  frontend:
    build:
      context: "sosusystem-frontend"
    image: "localhost:7002/sosusystem-frontend:${IMAGE_TAG}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
  backend:
    build:
      context: "sosusystem-backend"
    image: "localhost:7002/sosusystem-backend:${IMAGE_TAG}"
    container_name: "${API_CONT_NAME}"
    entrypoint: ["npm", "run", "start"]
    ports:
      - "${API_PORT}:80"
    depends_on:
      - mongodb_container
    environment:
      MONGODB_USER_NAME: admin
      MONGODB_USER_PASSWORD: adminExam2022
      MONGODB_DB_NAME: SOSU-Final-Release
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminExam2022
      MONGO_INITDB_DATABASE: SOSU-Final-Release
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
