version: "3.9"

services:
    backend:
        image: andersmadsen0/sosusystem-backend:${BUILD_NUMBER}
        restart: always
    frontend:
        image: andersmadsen0/sosusystem-frontend:${BUILD_NUMBER}
        restart: always
