version: "3.9"

services:
    mongodb:
      image: mongo
      ports:
        - "${DB_PORT}:27017"
      volumes:
        - mongo-prod:/data/db
        
      networks:
        - sosu-prod-network
    frontend:
        ports:
          - "${WEB_PORT}:80"
    backend:
        environment:
          MONGODB_PORT: "${DB_PORT}"
          JWT_SECRET_KEY: justALittleSecret
          JWT_EXPIRATION_TIME: 4300s
        entrypoint: ["npm", "run", "start"]
        ports:
          - "62001:3006"
        depends_on:
          - mongo
        networks:
        - sosu-prod-network
          
networks:
  sosu-prod-network:
    driver: bridge

volumes:
  mongo:
