version: "3.9"

services:
  frontend:
    build:
      context: "sosusystem-frontend"
    image: "localhost:7002/sosusystem-frontend:${IMAGE_TAG}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./data:/data/db
        environment: 
          - MONGODB_USER_NAME=admin
          - MONGODB_USER_PASSWORD=adminExam2022
          - MONGODB_DB_NAME=SOSU-Final-Release

  backend:
    build:
      context: "sosusystem-backend"
    image: "localhost:7002/sosusystem-backend:${IMAGE_TAG}"
    container_name: "${API_CONT_NAME}"
    entrypoint: ["npm", "run", "start"]
      - JWT_SECRET_KEY=justALittleSecret
      - JWT_EXPIRATION_TIME=4300s
      - MONGODB_USER_NAME=admin
      - MONGODB_USER_PASSWORD=adminExam2022
      - MONGODB_DB_NAME=SOSU-Final-Release
    ports:
      - "${API_PORT}:80"
    depends_on:
      - mongo
