version: "3.9"

services:
    
  frontend:
    build:
      context: "sosusystem-frontend"
    image: "localhost:7002/andersmadsen0/sosusystem-frontend:latest"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"

