version: "3.9"

services:
  frontend:
    build:
      context: "sosusystem-frontend"
    image: "${IMAGE_WEB}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
  backend:
    build:
      context: "sosusystem-backend"
    image: "${IMAGE_API}"
    container_name: "${API_CONT_NAME}"
    entrypoint: ["npm", "run", "start"]
    ports:
      - "${API_PORT}:3006"
    dns_search: ''
    environment:
      MONGODB_USER_NAME: admin
      MONGODB_USER_PASSWORD: adminExam2022
      MONGODB_DB_NAME: SOSU-Final-Release
      JWT_SECRET_KEY: justALittleSecret
      JWT_EXPIRATION_TIME: 4300s
