
version: "3.9"

services:
    mongo:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - mongo:/data/db
      networks:
        - sosu-network
    frontend:
        ports:
          - "61002:80"
    backend:
        environment:
          MONGODB_USER_NAME: admin
          MONGODB_USER_PASSWORD: adminExam2022
          MONGODB_DB_NAME: SOSU-Final-Release
          JWT_SECRET_KEY: justALittleSecret
          JWT_EXPIRATION_TIME: 4300s
        entrypoint: ["npm", "run", "start"]
        ports:
          - "61001:3006"
        depends_on:
          - mongo
        networks:
        - sosu-network
          
networks:
  sosu-network:
    driver: bridge

volumes:
  mongo:
